console.log("Arithmatic Operators");
let a = 10;
let b = 4;
console.log("a + b = ", a+b, " --> Addition");
console.log("a - b = ", a-b, " --> Subtraction");
console.log("a * b = ", a*b, " --> Multiplication");
console.log("a / b = ", a/b, " --> Division");
console.log("a ** b = ", a**b, " --> Exponentation");
console.log("a % b = ", a%b, " --> Modulus");
console.log("a++ = ", a++, " --> Increment");
console.log("++a = ", ++a, " --> Increment");
console.log("a-- = ", a--, " --> Decrement");
console.log("--a = ", --a, " --> Decrement");

// console.log("++a = ", ++a);
// console.log("a++ = ", a++);
// console.log("--a = ", --a);
// console.log("a-- = ", a--);
// console.log("a = ", a);
// console.log("a-- = ", a--);